name: my-app

services:
  app:
    build: .
    container_name: my-app
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PG_HOST: db
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DATABASE: postgres
    depends_on:
      - redis
      - db

  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5431:5432"
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
