name: my-app

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"

  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data://home/app/my-app/postgres/volume
  redis:
    image: redis:7-alpine
    container_name: redis
    volumes:
      - redis_data://home/app/my-app/redis/volume

volumes:
  postgres_data:
  redis_data:
